// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package sample_package_0308

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// Zhaoh0308Client is the client API for Zhaoh0308 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Zhaoh0308Client interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type zhaoh0308Client struct {
	cc grpc.ClientConnInterface
}

func NewZhaoh0308Client(cc grpc.ClientConnInterface) Zhaoh0308Client {
	return &zhaoh0308Client{cc}
}

func (c *zhaoh0308Client) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/sample_module_0308.sample_package_0308.zhaoh0308/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Zhaoh0308Server is the server API for Zhaoh0308 service.
// All implementations must embed UnimplementedZhaoh0308Server
// for forward compatibility
type Zhaoh0308Server interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedZhaoh0308Server()
}

// UnimplementedZhaoh0308Server must be embedded to have forward compatible implementations.
type UnimplementedZhaoh0308Server struct {
}

func (UnimplementedZhaoh0308Server) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedZhaoh0308Server) mustEmbedUnimplementedZhaoh0308Server() {}

// UnsafeZhaoh0308Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Zhaoh0308Server will
// result in compilation errors.
type UnsafeZhaoh0308Server interface {
	mustEmbedUnimplementedZhaoh0308Server()
}

func RegisterZhaoh0308Server(s grpc.ServiceRegistrar, srv Zhaoh0308Server) {
	s.RegisterService(&Zhaoh0308_ServiceDesc, srv)
}

func _Zhaoh0308_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Zhaoh0308Server).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sample_module_0308.sample_package_0308.zhaoh0308/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Zhaoh0308Server).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Zhaoh0308_ServiceDesc is the grpc.ServiceDesc for Zhaoh0308 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Zhaoh0308_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sample_module_0308.sample_package_0308.zhaoh0308",
	HandlerType: (*Zhaoh0308Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Zhaoh0308_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zhaoh0308.proto",
}
